paper:
	../../racket/racket/bin/racket typeset-grammar.rkt calc0-syntax.sexp
	../../racket/racket/bin/pdf-slatex paper.tex
	bibtex paper
	../../racket/racket/bin/pdf-slatex paper.tex
	../../racket/racket/bin/pdf-slatex paper.tex
